project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Juan Pablo Carranza"

  page-footer:
    left: "&copy; Copyright 2026, Juan Pablo Carranza"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  navbar:
    title: false
    left:
      - href: index.qmd
        text: Inicio

      - href: publicaciones/index.qmd
        text: Artículos científicos
        
      - href: congresos/index.qmd
        text: Publicaciones en congresos
        
      - href: divulgacion/index.qmd
        text: Divulgación de la ciencia
        
      - href: recursos/index.qmd
        text: Recursos pedagógicos


csl: journals.csl

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: false
    include-after-body:
      - file: lang-toggle.js



